# Generated by Django 5.2.5 on 2025-09-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
    ]
