# Generated by Django 5.2.5 on 2025-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_alter_tweet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
