# Generated by Django 5.2.5 on 2025-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_profile_bio_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(blank=True, default='Screenshot 2025-09-09 170334.png', null=True, upload_to='profile_images/'),
        ),
    ]
