# Generated by Django 5.2.5 on 2025-09-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_alter_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
